version: '3.9'

services:
  api:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: always
    ports:
      - 3000:3000

  postgres:
    image: postgres:latest
    container_name: appointments
    environment:
      POSTGRES_DB: appointments
      POSTGRES_USER: superboy
      POSTGRES_PASSWORD: sofast
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
